### ISSUE TITLE
jdk_switcher is missing from ci-minimal

### ISSUE THREAD

**Issue by BanzaiMan** [travis-infrastructure/packer-templates#1]
See https://secure.helpscout.net/conversation/95791441/16762/

https://github.com/travis-ci/travis-cookbooks/pull/483#issuecomment-114542679 which was misguided.

**Comment by meatballhat** [comment]
Now that I'm adding `jdk_switcher` to the minimal trusty image, I'm realizing that it's not much good without any JDK installations.  From the look of http://openjdk.java.net/install/ and what I know of Oracle, I'm assuming the recommend way of installing a given JDK on Ubuntu is via APT, which typically activates the installed JDK as the system default, at which point I don't understand the benefit of having `jdk_switcher` unless the intent is to switch between multiple JDKs within the context of a single job.
