### ISSUE TITLE
cmake missing

### ISSUE THREAD

**Issue by meatballhat** [travis-infrastructure/packer-templates#42]

**Comment by blueyed** [comment]
Will this be cmake 2.8.12.2-0ubuntu3 then, from Trusty?
Any chance to have a newer version in the default image?

**Comment by blueyed** [comment]
According to https://github.com/travis-ci/travis-cookbooks/pull/573#issuecomment-148980963 it would be cmake 3, right?

When will this be available / promoted to the Travis build machines?

**Comment by meatballhat** [comment]
@blueyed it's available now on the Trusty beta with `group: edge` :smiley_cat:

Full example:
- https://travis-ci.org/meatballhat/cloaked-octo-tyrion/builds/86041347
- https://github.com/meatballhat/cloaked-octo-tyrion/blob/3ac18724a4fb518c5a9625f1f16099d6bd0e80a9/.travis.yml

**Comment by blueyed** [comment]
Worked with `group: edge` back then, thanks for letting me know.
I assume that refers to some special early-beta program?
When will it be in the generic beta (if it is not by now), and is this documented somewhere?
