### ISSUE TITLE
Python default version on `dist: trusty` + `language: java` is `2.6.9`

### ISSUE THREAD

**Issue by cotsog** [travis-infrastructure/packer-templates#51]
Title says it all.

See build: https://travis-ci.org/cotsog/travis_ci_prod_trusty/builds/86113321.

When specifying `language: python`, default version is `2.7.10`.

Please consider notifying this customer when this is solved: https://secure.helpscout.net/conversation/130526367/21085/.

Thanks!

**Comment by MariadeAnton** [comment]
also happening on `dist:trusty` + `language: cpp`: https://travis-ci.org/nest/nest-simulator/jobs/85708207#L615

from: https://secure.helpscout.net/conversation/131384312/21245/

**Comment by meatballhat** [comment]
@MariadeAnton bumping to `group: edge` should show otherwise.  I haven't promoted the edge image with this fix to stable yet.

**Comment by joshk** [comment]
I think this might be related to https://github.com/travis-ci/travis-build/blob/master/lib/travis/build/script/python.rb#L6

When the Python build is choosen, the Python version of 2.7 is selected by default.

**Comment by meatballhat** [comment]
@joshk for `language: python` yep, but for cases where travis-build isn't doing a virtualenv activation, it's been the case that python2.7 is the default, so trying to keep that consistent is what this issue is about iiuc :+1:

**Comment by joshk** [comment]
Yep, i understood that, I just thought I would point to that code in case it was relevant.

**Comment by joshk** [comment]
:100:

**Comment by meatballhat** [comment]
This will be addressed for users not opting into `group: edge` as soon as the latest edge mega image is promoted to stable.
